In [1]:
import numpy as np
import main

In [2]:
material_1 = main.material_FDM(mat_id=0)
material_1.set_XS('XS_scatter',[[0,0.01422],[0,0]])
material_1.set_XS('Diffusion_coef',[1.3880,0.3842])
material_1.set_XS('XS_absorption',[0.009710,0.121800])
material_1.set_XS('XS_nu_fission',[0.006499,0.142900])
material_1.set_XS('XS_fission_spectrum',[1.0,0.0])

In [3]:
material_2 = main.material_FDM(mat_id=1)
material_2.set_XS('XS_scatter',[[0,0.02838],[0,0]])
material_2.set_XS('Diffusion_coef',[1.4470,0.3748])
material_2.set_XS('XS_absorption',[0.009447,0.089290])
material_2.set_XS('XS_nu_fission',[0.006505,0.132500])
material_2.set_XS('XS_fission_spectrum',[1.0,0.0])

In [4]:
material_3 = main.material_FDM(mat_id=2)
material_3.set_XS('XS_scatter',[[0,0.01730],[0,0]])
material_3.set_XS('Diffusion_coef',[1.5450,0.3126])
material_3.set_XS('XS_absorption',[0.000444,0.008736])
material_3.set_XS('XS_nu_fission',[0,0])
material_3.set_XS('XS_fission_spectrum',[1.0,0.0])

In [5]:
geo = main.geometry_FDM(x_block=4,y_block=4)
sl = slice(0, 4, None)
# W
geo.set_block_mat(material_3,sl,sl)
# A
geo.set_block_mat(material_1,0,0)
geo.set_block_mat(material_1,2,0)
geo.set_block_mat(material_1,1,1)
geo.set_block_mat(material_1,0,2)
geo.set_block_mat(material_1,2,2)
# B
geo.set_block_mat(material_2,1,0)
geo.set_block_mat(material_2,0,1)
geo.set_block_mat(material_2,2,1)
geo.set_block_mat(material_2,1,2)

geo.set_block_size(x_size=[4,8,8,8],y_size=[4,8,8,8])
geo.set_discretized_num(x_dim=[8,16,16,16],y_dim=[8,16,16,16])
# geo.set_discretized_num(x_dim=[4,8,8,8],y_dim=[4,8,8,8])
geo.check_blocks()

Material layout:
[[0 1 0 2]
 [1 0 1 2]
 [0 1 0 2]
 [2 2 2 2]]
Block size:
x:[4, 8, 8, 8]
y:[4, 8, 8, 8]
Discretization number:
x:[8, 16, 16, 16]
y:[8, 16, 16, 16]


In [6]:
case = main.solver_FDM(group_num=2)
case.add_material([material_1,material_2,material_3])
case.set_geometry(geo)

In [7]:
case.solve_source_iter(max_iter=100,k_tolerance=1e-4,flux_tolerance=1e-3,initial_k=1.0)

Iteration 1: Eigenvalue k = 0.540365673575271
Iteration 2: Eigenvalue k = 1.7407017235566278
Iteration 3: Eigenvalue k = 1.7760785196274786
Iteration 4: Eigenvalue k = 1.8141842751846398
Iteration 5: Eigenvalue k = 1.8232816521211102
Iteration 6: Eigenvalue k = 1.8308025935329586
Iteration 7: Eigenvalue k = 1.833198052450287
Iteration 8: Eigenvalue k = 1.834956686785868
Iteration 9: Eigenvalue k = 1.8355942413833328
Iteration 10: Eigenvalue k = 1.8360258751153262
Iteration 11: Eigenvalue k met the criterion and k = 1.836195028697357
