In [1]:
import main

In [2]:
import numpy as np

In [3]:
material_1 = main.material_FDM(mat_id=0)
material_1.set_XS('XS_scatter',[[0,0.01],[0,0]])
material_1.set_XS('Diffusion_coef',[1.4,0.4])
material_1.set_XS('XS_absorption',[0.01,0.15])
# material_1.set_XS('XS_absorption',[0.02,0.15])
material_1.set_XS('XS_nu_fission',[0.007,0.2])
material_1.set_XS('XS_fission_spectrum',[1.0,0.0])

In [4]:
material_2 = main.material_FDM(mat_id=1)
material_2.set_XS('XS_scatter',[[0,0.01],[0,0]])
material_2.set_XS('Diffusion_coef',[1.4,0.4])
material_2.set_XS('XS_absorption',[0.01,0.15])
# material_2.set_XS('XS_absorption',[0.02,0.15])
material_2.set_XS('XS_nu_fission',[0.007,0.2])
material_2.set_XS('XS_fission_spectrum',[1.0,0.0])

In [5]:
material_3 = main.material_FDM(mat_id=2)
material_3.set_XS('XS_scatter',[[0,0.01],[0,0]])
material_3.set_XS('Diffusion_coef',[1.3,0.5])
material_3.set_XS('XS_absorption',[0.008,0.05])
# material_3.set_XS('XS_absorption',[0.018,0.05])
material_3.set_XS('XS_nu_fission',[0.003,0.06])
material_3.set_XS('XS_fission_spectrum',[1.0,0.0])

In [6]:
geo = main.geometry_FDM(x_block=3,y_block=3)
sl = slice(0, 3, None)
geo.set_block_mat(material_3,sl,sl)
geo.set_block_mat(material_1,1,1)
geo.set_block_mat(material_2,1,0)
geo.set_block_mat(material_2,0,1)

geo.set_block_size(x_size=[24,32,24],y_size=[24,32,24])
geo.set_discretized_num(x_dim=[24,32,24],y_dim=[24,32,24])
geo.check_blocks()

Material layout:
[[2 1 2]
 [1 0 2]
 [2 2 2]]
Block size:
x:[24, 32, 24]
y:[24, 32, 24]
Discretization number:
x:[24, 32, 24]
y:[24, 32, 24]


In [7]:
case = main.solver_FDM(folder_name='TWIGL_Seed_Blanket_2D',group_num=2)
case.add_material([material_1,material_2,material_3])
case.set_geometry(geo)

In [8]:
case.solve_source_iter_correct(max_iter=50,k_tolerance=1e-5,flux_tolerance=1e-3,initial_k=1.0)

Iteration 1: Eigenvalue k = 0.8446669513193322
Error of fission source εq = 93.80720692159554
Iteration 2: Eigenvalue k = 0.8899489163397002
Error of fission source εq = 2.4242628724761297
Iteration 3: Eigenvalue k = 0.8994594776166441
Error of fission source εq = 0.5239533647791025
Iteration 4: Eigenvalue k = 0.9038026479314233
Error of fission source εq = 0.22538331462119918
Iteration 5: Eigenvalue k = 0.9064220494043878
Error of fission source εq = 0.12536047637440517
Iteration 6: Eigenvalue k = 0.9081900679307715
Error of fission source εq = 0.0803268662436691
Iteration 7: Eigenvalue k = 0.9094479494340283
Error of fission source εq = 0.05584263729750807
Iteration 8: Eigenvalue k = 0.9103687896329569
Error of fission source εq = 0.040708838787608476
Iteration 9: Eigenvalue k = 0.9110545506517276
Error of fission source εq = 0.030512445372855825
Iteration 10: Eigenvalue k = 0.9115708863732314
Error of fission source εq = 0.02324199519733913
Iteration 11: Eigenvalue k = 0.91196251561