In [1]:
import main

In [2]:
import numpy as np

In [3]:
material_1 = main.material_FDM(mat_id=0)
material_1.set_XS('XS_scatter',[[0,0.01],[0,0]])
material_1.set_XS('Diffusion_coef',[1.4,0.4])
material_1.set_XS('XS_absorption',[0.01,0.15])
# material_1.set_XS('XS_absorption',[0.02,0.15])
material_1.set_XS('XS_nu_fission',[0.007,0.2])
material_1.set_XS('XS_fission_spectrum',[1.0,0.0])

In [4]:
material_2 = main.material_FDM(mat_id=1)
material_2.set_XS('XS_scatter',[[0,0.01],[0,0]])
material_2.set_XS('Diffusion_coef',[1.4,0.4])
material_2.set_XS('XS_absorption',[0.01,0.15])
# material_2.set_XS('XS_absorption',[0.02,0.15])
material_2.set_XS('XS_nu_fission',[0.007,0.2])
material_2.set_XS('XS_fission_spectrum',[1.0,0.0])

In [5]:
material_3 = main.material_FDM(mat_id=2)
material_3.set_XS('XS_scatter',[[0,0.01],[0,0]])
material_3.set_XS('Diffusion_coef',[1.3,0.5])
material_3.set_XS('XS_absorption',[0.008,0.05])
# material_3.set_XS('XS_absorption',[0.018,0.05])
material_3.set_XS('XS_nu_fission',[0.003,0.06])
material_3.set_XS('XS_fission_spectrum',[1.0,0.0])

In [6]:
geo = main.geometry_FDM(x_block=3,y_block=3)
sl = slice(0, 3, None)
geo.set_block_mat(material_3,sl,sl)
geo.set_block_mat(material_1,1,1)
geo.set_block_mat(material_2,1,0)
geo.set_block_mat(material_2,0,1)

geo.set_block_size(x_size=[24,32,24],y_size=[24,32,24])
geo.set_discretized_num(x_dim=[24,32,24],y_dim=[24,32,24])
geo.check_blocks()

Material layout:
[[2 1 2]
 [1 0 2]
 [2 2 2]]
Block size:
x:[24, 32, 24]
y:[24, 32, 24]
Discretization number:
x:[24, 32, 24]
y:[24, 32, 24]


In [7]:
case = main.solver_FDM(group_num=2)
case.add_material([material_1,material_2,material_3])
case.set_geometry(geo)

In [9]:
case.solve_source_iter_correct(max_iter=50,k_tolerance=1e-5,flux_tolerance=1e-3,initial_k=1.0)

Iteration 1: Eigenvalue k = 0.8444053663936574
Iteration 2: Eigenvalue k = 0.8904241589553132
Iteration 3: Eigenvalue k = 0.9002108419561495
Iteration 4: Eigenvalue k = 0.9046453464053824
Iteration 5: Eigenvalue k = 0.9073006453047352
Iteration 6: Eigenvalue k = 0.9090871557227065
Iteration 7: Eigenvalue k = 0.9103571380846673
Iteration 8: Eigenvalue k = 0.9112871867044968
Iteration 9: Eigenvalue k = 0.911980509550697
Iteration 10: Eigenvalue k = 0.9125032612928043
Iteration 11: Eigenvalue k = 0.9129003956796563
Iteration 12: Eigenvalue k = 0.9132036615941167
Iteration 13: Eigenvalue k = 0.9134360800758539
Iteration 14: Eigenvalue k = 0.9136146528943756
Iteration 15: Eigenvalue k = 0.9137521004610466
Iteration 16: Eigenvalue k = 0.9138580284893163
Iteration 17: Eigenvalue k = 0.9139397389645896
Iteration 18: Eigenvalue k = 0.914002809190483
Iteration 19: Eigenvalue k = 0.9140515137945274
Iteration 20: Eigenvalue k = 0.9140891370901489
Iteration 21: Eigenvalue k = 0.914118206987393
Iter