In [1]:
import numpy as np
import main

In [2]:
M_ls = []

In [3]:
M = main.material_FDM(mat_id=1)
M.set_XS('XS_scatter',[[0,1.74200E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.41760E+00,3.73350E-01])
M.set_XS('XS_absorption',[8.55000E-03,6.66900E-02])
M.set_XS('XS_nu_fission',[5.36000E-03,1.04330E-01])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=2)
M.set_XS('XS_scatter',[[0,1.69400E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.41920E+00,3.73700E-01])
M.set_XS('XS_absorption',[8.82000E-03,7.60600E-02])
M.set_XS('XS_nu_fission',[6.01000E-03,1.24720E-01])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=3)
M.set_XS('XS_scatter',[[0,1.65800E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.42650E+00,3.74240E-01])
M.set_XS('XS_absorption',[9.02000E-03,8.35900E-02])
M.set_XS('XS_nu_fission',[6.53000E-03,1.41200E-01])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=4)
M.set_XS('XS_scatter',[[0,1.75651E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.47410E+00,2.96746E-01])
M.set_XS('XS_absorption',[1.55610E-03,1.78450E-02])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=5)
M.set_XS('XS_scatter',[[0,2.90300E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.45540E+00,2.89940E-01])
M.set_XS('XS_absorption',[4.70000E-04,9.49000E-03])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=6)
M.set_XS('XS_scatter',[[0,1.75651E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.47410E+00,2.96746E-01])
M.set_XS('XS_absorption',[1.55610E-03,1.78450E-02])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=7)
M.set_XS('XS_scatter',[[0,1.75651E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.47410E+00,2.96746E-01])
M.set_XS('XS_absorption',[1.55610E-03,1.78450E-02])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

In [4]:
geo = main.geometry_FDM(x_block=9,y_block=9)
layout = np.array([[1,2,1,2,1,2,1,3,6],[2,1,2,1,2,1,3,3,6],[1,2,1,2,1,2,1,3,6],[2,1,2,1,2,1,3,3,6],[1,2,1,2,2,2,3,7,5],[2,1,2,1,2,3,3,6,5],[1,3,1,3,3,3,7,5,5],[3,3,3,3,7,4,5,5,5],[4,4,4,4,5,5,5,5,5]],dtype=np.int32)

geo.set_block_mat_by_array(layout)

geo.set_block_size(x_size=[10.804,21.608,21.608,21.608,21.608,21.608,21.608,21.608,21.608],y_size=[10.804,21.608,21.608,21.608,21.608,21.608,21.608,21.608,21.608])
# geo.set_discretized_num(x_dim=[8,16,16,16],y_dim=[8,16,16,16])
# geo.set_discretized_num(x_dim=[4,8,8,8],y_dim=[4,8,8,8])
geo.set_discretized_num(x_dim=[10,20,20,20,20,20,20,20,20],y_dim=[10,20,20,20,20,20,20,20,20])
geo.check_blocks()

Material layout:
[[1 2 1 2 1 2 1 3 6]
 [2 1 2 1 2 1 3 3 6]
 [1 2 1 2 1 2 1 3 6]
 [2 1 2 1 2 1 3 3 6]
 [1 2 1 2 2 2 3 7 5]
 [2 1 2 1 2 3 3 6 5]
 [1 3 1 3 3 3 7 5 5]
 [3 3 3 3 7 4 5 5 5]
 [4 4 4 4 5 5 5 5 5]]
Block size:
x:[10.804, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608]
y:[10.804, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608]
Discretization number:
x:[10, 20, 20, 20, 20, 20, 20, 20, 20]
y:[10, 20, 20, 20, 20, 20, 20, 20, 20]


In [5]:
case = main.solver_FDM(group_num=2)
case.add_material(M_ls)
case.set_geometry(geo)

In [6]:
case.solve_source_iter_correct(max_iter=100,k_tolerance=1e-5,flux_tolerance=1e-3,initial_k=1.0)

Iteration 1: Eigenvalue k = 1.2514159116618049
Iteration 2: Eigenvalue k = 1.2577269177822106
Iteration 3: Eigenvalue k = 1.2616656363073062
Iteration 4: Eigenvalue k = 1.264260207180103
Iteration 5: Eigenvalue k = 1.2660815991546244
Iteration 6: Eigenvalue k = 1.2674259051024768
Iteration 7: Eigenvalue k = 1.2684577833813022
Iteration 8: Eigenvalue k = 1.2692749308669549
Iteration 9: Eigenvalue k = 1.2699385326380581
Iteration 10: Eigenvalue k = 1.2704886769489583
Iteration 11: Eigenvalue k = 1.2709526488453804
Iteration 12: Eigenvalue k = 1.271349630517804
Iteration 13: Eigenvalue k = 1.271693487329894
Iteration 14: Eigenvalue k = 1.271994484853228
Iteration 15: Eigenvalue k = 1.272260383848228
Iteration 16: Eigenvalue k = 1.272497159860956
Iteration 17: Eigenvalue k = 1.2727094888618675
Iteration 18: Eigenvalue k = 1.272901082819512
Iteration 19: Eigenvalue k = 1.2730749265163175
Iteration 20: Eigenvalue k = 1.2732334478579719
Iteration 21: Eigenvalue k = 1.2733786424573346
Iteratio