In [1]:
import numpy as np
import main

In [2]:
M_ls = []

In [3]:
M = main.material_FDM(mat_id=1)
M.set_XS('XS_scatter',[[0,1.74200E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.41760E+00,3.73350E-01])
M.set_XS('XS_absorption',[8.55000E-03,6.66900E-02])
M.set_XS('XS_nu_fission',[5.36000E-03,1.04330E-01])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=2)
M.set_XS('XS_scatter',[[0,1.69400E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.41920E+00,3.73700E-01])
M.set_XS('XS_absorption',[8.82000E-03,7.60600E-02])
M.set_XS('XS_nu_fission',[6.01000E-03,1.24720E-01])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=3)
M.set_XS('XS_scatter',[[0,1.65800E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.42650E+00,3.74240E-01])
M.set_XS('XS_absorption',[9.02000E-03,8.35900E-02])
M.set_XS('XS_nu_fission',[6.53000E-03,1.41200E-01])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=4)
M.set_XS('XS_scatter',[[0,1.75651E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.47410E+00,2.96746E-01])
M.set_XS('XS_absorption',[1.55610E-03,1.78450E-02])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=5)
M.set_XS('XS_scatter',[[0,2.90300E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.45540E+00,2.89940E-01])
M.set_XS('XS_absorption',[4.70000E-04,9.49000E-03])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=6)
M.set_XS('XS_scatter',[[0,1.75651E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.47410E+00,2.96746E-01])
M.set_XS('XS_absorption',[1.55610E-03,1.78450E-02])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

M = main.material_FDM(mat_id=7)
M.set_XS('XS_scatter',[[0,1.75651E-02],[0,0]])
M.set_XS('Diffusion_coef',[1.47410E+00,2.96746E-01])
M.set_XS('XS_absorption',[1.55610E-03,1.78450E-02])
M.set_XS('XS_nu_fission',[0.0,0.0])
M.set_XS('XS_fission_spectrum',[1.0,0.0])
M_ls.append(M)

In [4]:
geo = main.geometry_FDM(x_block=9,y_block=9)
layout = np.array([[1,2,1,2,1,2,1,3,6],[2,1,2,1,2,1,3,3,6],[1,2,1,2,1,2,1,3,6],[2,1,2,1,2,1,3,3,6],[1,2,1,2,2,2,3,7,5],[2,1,2,1,2,3,3,6,5],[1,3,1,3,3,3,7,5,5],[3,3,3,3,7,4,5,5,5],[4,4,4,4,5,5,5,5,5]],dtype=np.int32)

geo.set_block_mat_by_array(layout)

geo.set_block_size(x_size=[10.804,21.608,21.608,21.608,21.608,21.608,21.608,21.608,21.608],y_size=[10.804,21.608,21.608,21.608,21.608,21.608,21.608,21.608,21.608])
geo.set_discretized_num(x_dim=[10,20,20,20,20,20,20,20,20],y_dim=[10,20,20,20,20,20,20,20,20])
geo.check_blocks()

Material layout:
[[1 2 1 2 1 2 1 3 6]
 [2 1 2 1 2 1 3 3 6]
 [1 2 1 2 1 2 1 3 6]
 [2 1 2 1 2 1 3 3 6]
 [1 2 1 2 2 2 3 7 5]
 [2 1 2 1 2 3 3 6 5]
 [1 3 1 3 3 3 7 5 5]
 [3 3 3 3 7 4 5 5 5]
 [4 4 4 4 5 5 5 5 5]]
Block size:
x:[10.804, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608]
y:[10.804, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608, 21.608]
Discretization number:
x:[10, 20, 20, 20, 20, 20, 20, 20, 20]
y:[10, 20, 20, 20, 20, 20, 20, 20, 20]


In [5]:
case = main.solver_FDM(folder_name='ZION_1_2D',group_num=2)
case.add_material(M_ls)
case.set_geometry(geo)

In [6]:
case.solve_source_iter_correct(max_iter=100,k_tolerance=1e-5,flux_tolerance=1e-3,initial_k=1.0)

Iteration 1: Eigenvalue k = 1.2513271643197812
Error of fission source εq = 0.30758774276120543
Iteration 2: Eigenvalue k = 1.2576676626632497
Error of fission source εq = 0.2434925706834454
Iteration 3: Eigenvalue k = 1.2616203089777263
Error of fission source εq = 0.15598558063854978
Iteration 4: Eigenvalue k = 1.2642227902982002
Error of fission source εq = 0.10971835346496903
Iteration 5: Eigenvalue k = 1.2660492223054918
Error of fission source εq = 0.08212155878609033
Iteration 6: Eigenvalue k = 1.2673970027948867
Error of fission source εq = 0.0642230365283962
Iteration 7: Eigenvalue k = 1.268431417691267
Error of fission source εq = 0.05189131952025684
Iteration 8: Eigenvalue k = 1.2692504988841187
Error of fission source εq = 0.04300746465281035
Iteration 9: Eigenvalue k = 1.2699156250136705
Error of fission source εq = 0.036383524496365935
Iteration 10: Eigenvalue k = 1.2704670033755021
Error of fission source εq = 0.031286213089455686
Iteration 11: Eigenvalue k = 1.270931996